### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by derritter88** [Kailona/kailona-fhir-server#1]
Hello there,

I cloned the Git repo but inside I find a lot of "change-password" values which are not being documented.

Should they be changed or not?!

**Comment by ayselafsar** [comment]
Hey @derritter88 

Yes, we recommend to change all of these values with strong passwords for security.

Also, we recommend to provide FHIR server access to the Nextcloud instance only in the same network, no need to open FHIR server to public internet for Kailona.

**Comment by derritter88** [comment]
Hello @ayselafsar ,

thanks for clarification!
I have just checked the ports and as far as I can see the PostgreSQL container listens on 0.0.0.0/0 - so far I cannot see any possiblity to have it listen only on localhost or 127.0.0.1

**Comment by makuser** [comment]
> Also, we recommend to provide FHIR server access to the Nextcloud instance only in the same network, no need to open FHIR server to public internet for Kailona.

Interesting, that is something that needs to be documented somewhere. I then also wonder, why the webapp tries to talk to the fhir domain sometimes?

**Comment by ayselafsar** [comment]
> I have just checked the ports and as far as I can see the PostgreSQL container listens on 0.0.0.0/0 - so far I cannot see any possiblity to have it listen only on localhost or 127.0.0.1

I think this is something with postgres docker image, i would refer to [here](https://hub.docker.com/_/postgres)

**Comment by ayselafsar** [comment]
> Interesting, that is something that needs to be documented somewhere.

Good idea, we will try to document it ASAP. or would like to accept PR.

> I then also wonder, why the webapp tries to talk to the fhir domain sometimes?

We use a FHIR gateway running in nextcloud server side, forwarding FHIR requests to FHIR server, so the client application does not make any direct call to FHIR server. It even does not know FHIR server's credentials. However. its data structure and API endpoints are the same with FHIR server, so you might get confused. If the url is something like `.../apps/ehr/fhir/...`, that is the gateway, not FHIR server url. Otherwise, please let me know the endpoint. Thanks!

I just noticed your issue [here](https://github.com/Kailona/ehr/issues/78) related to this. It looks like a bug in the FHIR gateway. We will investigate it.

**Comment by derritter88** [comment]
> We use a FHIR gateway running in nextcloud server side, forwarding FHIR requests to FHIR server, so the client application does not make any direct call to FHIR server. It even does not know FHIR server's credentials.

So in general I could run the IBM FHIR directly & without Docker on my system and use my existing PostgreSQL-Cluster - right?

**Comment by makuser** [comment]
> > We use a FHIR gateway running in nextcloud server side, forwarding FHIR requests to FHIR server, so the client application does not make any direct call to FHIR server. It even does not know FHIR server's credentials.
> 
> So in general I could run the IBM FHIR directly & without Docker on my system and use my existing PostgreSQL-Cluster - right?

Yes of course, the dockerized approach is just simpler to setup, but you could pull the ibm fhir repo and make/build it yourself, or also download a release from there and install that. You then have to configure it on your own as well.

By the way, if it is just because of your existing cluster, you could also run the fhir server in docker and have it use your PostgreSQL cluster.

**Comment by derritter88** [comment]
Just an off-topic question: I've recognised that there is a "Live (Alpha)" button on the documentation page which lead to [this](https://app.kailona.org/login) page.
Is there a possibility to get access to it?

**Comment by makuser** [comment]
> > Interesting, that is something that needs to be documented somewhere.
> 
> Good idea, we will try to document it ASAP. or would like to accept PR.

#2 amongst other things (primarily updating the server to the latest version) adds a password change notice to the README.md.
